name: Linux

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Conan
      uses: turtlebrowser/get-conan@main

    - name: Build
      run: |
        mkdir build && cd build
        conan install .. --build --profile ../.conan/linux.conf
        cmake ..
        cmake --build .

    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: build

  tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Artifact
      uses: actions/download-artifact@v2
      with:
        name: build-artifact
        path: build

    - name: Tests
      run: |
        ctest -C Debug
