name: Linux

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Conan
      uses: turtlebrowser/get-conan@main

    - name: Build
      run: |
        mkdir build && cd build
        conan install .. --build missing
        cmake ..
        cmake --build .

    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: build
