name: Windows

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

env:
    BUILD_TYPE: Release

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Vcpkg
              uses: lukka/run-vcpkg@v11
              with:
                  vcpkgGitCommitId: 4a600e9fea71bd7872080cbb716797e04d30e6d3

            - name: Build
              run: |
                  mkdir build && cd build
                  cmake .. --preset windows -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTING=True
                  cmake --build . --config ${{env.BUILD_TYPE}}

            - name: Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build-artifact
                  path: build

    tests:
        runs-on: windows-latest
        needs: [build]
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Artifact
              uses: actions/download-artifact@v4
              with:
                  name: build-artifact
                  path: build

            - name: Tests
              run: |
                  cd build
                  ctest -C Release
